apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- overlays/argocd-repo-server-deployment.yaml
- overlays/argocd-server-deployment.yaml
- overlays/argocd-application-controller-statefulset.yaml


images:
- name: quay.io/34fathombelow/argocd
  newName: quay.io/34fathombelow/argocd
  newTag: latest
- name: quay.io/argoproj/argocd
  newName: quay.io/34fathombelow/argocd
  newTag: v3.0.0
resources:
- ../../base/application-controller
- ../../base/applicationset-controller
- ../../base/dex
- ../../base/repo-server
- ../../base/server
- ../../base/config
- ../../base/notification
- ./redis-ha
