name: Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  set_tag:
    if: github.repository == '34fathombelow/cosign_test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          path: src/github.com/argoproj/argo-cd

      # set image tag
      - run: echo "tag=$(cat ./VERSION)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        id: image
        working-directory: ./src/github.com/argoproj/argo-cd

  build_and_publish:
    needs: [set_tag]
    permissions:
      contents: write  # for git to push upgrade commit if not already deployed
      packages: write  # for pushing packages to GHCR, which is used by cd.apps.argoproj.io to avoid polluting Quay with tags
      id-token: write # for creating OIDC tokens for signing.
    if: ${{ github.repository == '34fathombelow/cosign_test' && github.event_name == 'push' }}
    uses: ./.github/workflows/image-reuse.yaml
    with:
      quay_image_name: quay.io/34fathombelow/argocd:latest
      ghcr_image_name: ghcr.io/34fathombelow/cosign_test:${{ needs.set_tag.image.outputs.tag }}
      go-version: 1.18 # Note: cannot use env variables to set go-version (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      platforms: linux/amd64
      push: true
    secrets:
      quay_username: ${{ secrets.RELEASE_QUAY_USERNAME }}
      quay_password: ${{ secrets.RELEASE_QUAY_TOKEN }}
      ghcr_username: ${{ github.actor }}
      ghcr_password: ${{ secrets.GITHUB_TOKEN }}

  build_only:
    needs: [set_tag]
    permissions:
      contents: read  # for git to push upgrade commit if not already deployed
    #  packages: write  # for pushing packages to GHCR, which is used by cd.apps.argoproj.io to avoid polluting Quay with tags
    #  id-token: write # for creating OIDC tokens for signing.
    if: ${{ github.repository == '34fathombelow/cosign_test' && github.event_name != 'push' }}
    uses: ./.github/workflows/image-reuse.yaml
    with:
      go-version: 1.18 # Note: cannot use env variables to set go-version (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      platforms: linux/amd64
      push: false

      # deploy
#      - run: git clone "https://$TOKEN@github.com/argoproj/argoproj-deployments"
#        if: github.event_name == 'push'
#        env:
#          TOKEN: ${{ secrets.TOKEN }}
#      - run: |
#          docker run -u $(id -u):$(id -g) -v $(pwd):/src -w /src --rm -t ghcr.io/argoproj/argo-cd/argocd:${{ steps.image.outputs.tag }} kustomize edit set image quay.io/argoproj/argocd=ghcr.io/argoproj/argo-cd/argocd:${{ steps.image.outputs.tag }}
#          git config --global user.email 'ci@argoproj.com'
#          git config --global user.name 'CI'
#          git diff --exit-code && echo 'Already deployed' || (git commit -am 'Upgrade argocd to ${{ steps.image.outputs.tag }}' && git push)
#        if: github.event_name == 'push'
#        working-directory: argoproj-deployments/argocd
      # TODO: clean up old images once github supports it: https://github.community/t5/How-to-use-Git-and-GitHub/Deleting-images-from-GitHub-Package-Registry/m-p/41202/thread-id/9811
