name: Publish ArgoCD Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  env.GOLANG_VERSION: '1.18'

jobs:
  release-argo-cd:
    permissions:
      contents: read
      id-token: write # for creating OIDC tokens for signing.
      packages: write # used to push images to `ghcr.io` if used.
    uses: ./.github/workflows/image-reuse.yaml
    with:
      image_tags: quay.io/34fathombelow/argocd:${{ github.ref_name }}
      go-version: 1.18 # Note: cannot use env variables to set go-version (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      platforms: linux/amd64,linux/arm64
      push: true
    secrets:
      quay_username: ${{ secrets.RELEASE_QUAY_USERNAME }}
      quay_password: ${{ secrets.RELEASE_QUAY_TOKEN }}
  
  argocd-provenance:
      needs: [release-argo-cd]
      permissions:
        actions: read # for detecting the Github Actions environment.
        id-token: write # for creating OIDC tokens for signing.
        packages: write # for uploading attestations. (https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#known-issues)
      # Must be refernced by a tag. https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#referencing-the-slsa-generator
      uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
      with:
        image: quay.io/34fathombelow/argocd
        digest: ${{ needs.release-argo-cd.outputs.image-digest }}
        registry-username: ${{ github.actor }} # Should be moved into a secret when #1409 is merged (github.com/slsa-framework/slsa-github-generator/pull/1409)
      secrets:
        registry-password: ${{ secrets.RELEASE_QUAY_TOKEN }}

  goreleaser:
    permissions:
      contents: write # used for uploading assets
    runs-on: ubuntu-22.04
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Golang
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Set environment variables for ldflags
        id: set_ldflag
        run: |
          echo "KUBECTL_VERSION=$(go list -m k8s.io/client-go | head -n 1 | rev | cut -d' ' -f1 | rev)" >> $GITHUB_ENV
          echo "GIT_TREE_STATE=$(if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v4.1.0
        id: run-goreleaser
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBECTL_VERSION: ${{ env.KUBECTL_VERSION }} 
          GIT_TREE_STATE: ${{ env.GIT_TREE_STATE }}

      - name: Generate subject
        id: hash
        env:
          ARTIFACTS: "${{ steps.run-goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail

          hashes=$(echo $ARTIFACTS | jq --raw-output '.[] | {name, "digest": (.extra.Digest // .extra.Checksum)} | select(.digest) | {digest} + {name} | join("  ") | sub("^sha256:";"")' | base64 -w0)
          if test "$hashes" = ""; then # goreleaser < v1.13.0
            checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
            hashes=$(cat $checksum_file | base64 -w0)
          fi
          echo "hashes=$hashes" >> $GITHUB_OUTPUT

  provenance:
    needs: [goreleaser]
    permissions:
      actions: read # for detecting the Github Actions environment
      id-token: write # Needed for provenance signing and ID
      contents: write #  Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.goreleaser.outputs.hashes }}"
      provenance-name: "argocd-${{ github.ref_name }}-cli.intoto.jsonl"
      upload-assets: true


#  Sbom-and-Signatures:
#    name: Create Sbom and sign assets
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
#        with:
#          fetch-depth: 0
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Setup Golang
#        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
#        with:
#          go-version: ${{ env.GOLANG_VERSION }}
#
#      - name: Generate SBOM (spdx)
#        id: spdx-builder
#        env:
#          # defines the spdx/spdx-sbom-generator version to use.
#          SPDX_GEN_VERSION: v0.0.15
#          # defines the sigs.k8s.io/bom version to use.
#          SIGS_BOM_VERSION: v0.4.1
#          # comma delimited list of project relative folders to inspect for package
#          # managers (gomod, yarn, npm).
#          PROJECT_FOLDERS: ".,./ui" 
#          # full qualified name of the docker image to be inspected
#          DOCKER_IMAGE: ${{env.IMAGE_NAMESPACE}}/argocd:v${{env.TARGET_VERSION}}
#        run: |
#          yarn install --cwd ./ui
#          go install github.com/spdx/spdx-sbom-generator/cmd/generator@$SPDX_GEN_VERSION
#          go install sigs.k8s.io/bom/cmd/bom@$SIGS_BOM_VERSION
#
#          # Generate SPDX for project dependencies analyzing package managers
#          for folder in $(echo $PROJECT_FOLDERS | sed "s/,/ /g")
#          do
#            generator -p $folder -o /tmp
#          done
#
#          # Generate SPDX for binaries analyzing the docker image
#          if [[ ! -z $DOCKER_IMAGE ]]; then
#            bom generate -o /tmp/bom-docker-image.spdx -i $DOCKER_IMAGE
#          fi
#
#          cd /tmp && tar -zcf sbom.tar.gz *.spdx
#
