name: Init ArgoCD Release
on:
  workflow_dispatch:
    inputs:
      checkout_branch:
        description: 'Which to branch to checkout'
        required: true
        type: string

      tag_version:
        description: ''
        required: true
        type: string

permissions:
  contents: read

jobs:
  prepare-release:
    permissions:
      contents: write # To push changes to release branch
    name: Perform automatic pre-release on ${{ github.ref }}
  # if: github.repository == 'argoproj/argo-cd'
    runs-on: ubuntu-22.04
    env:
      SOURCE_TAG: ${{ github.ref }}
      TARGET_VERSION:
      TARGET_BRANCH:
      RELEASE_TAG:


    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Check if the published tag is well formed and setup vars
      #  id: vars
      #  run: ./.github/workflows/scripts/pre-release-checks.sh



      - name: Checkout corresponding release branch
        run: |
          set -ue
          echo "Switching to release branch '${TARGET_BRANCH}'"
          if ! git checkout ${TARGET_BRANCH}; then
            echo "::error::Checking out release branch '${TARGET_BRANCH}' for target version '${TARGET_VERSION}' (tagged '${RELEASE_TAG}') failed. Does it exist in repo?"
            exit 1
          fi

      - name: Create VERSION information
        run: |
          set -ue
          echo "Bumping version from $(cat VERSION) to ${TARGET_VERSION}"
          echo "${TARGET_VERSION}" > VERSION
          git commit -m "Bump version to ${TARGET_VERSION}" VERSION

      - name: Generate new set of manifests
        run: |
          set -ue
          make install-codegen-tools-local
          make manifests-local VERSION=${TARGET_VERSION}
          git diff
          git commit manifests/ -m "Bump version to ${TARGET_VERSION}"

